### PR TITLE
Fix [BUG-92] Non-Uniq Modules customCircleMarker and CustomCircleMarker

### PR DESCRIPTION
**Pull request by PluggPreagar**
according J03 - could you @bastiion review it - thx

### CODE REVIEW

**Comment by PluggPreagar** [comment]
at my side compiling is good - but get new error "cannot create cluster TypeError: leafletMarkerFactory is not a function
    filterDataLayer MarkerClusterLayer.tsx:40
    filterDataLayer MarkerClusterLayer.tsx:39
    MarkerClusterLayer MarkerClusterLayer.tsx:53" -- will re-check or do you know about this error already?

**Comment by PluggPreagar** [comment]
grafik

**Comment by PluggPreagar** [comment]
Part II was lost - renaming var to customCircleMarkerFactory in renamed file ... b6179c109d12e23322d512bb55e19c6b91f3936c

**Comment by bastiion** [comment]
Thank you for fixing that. Another option would be to simply delete `CustomCircleMarker.tsx` because, this is not used anymore. It was the `react` way of creating Markers, but unfortunately MarkerCluster with Markers of react-leaflet seems broken, so I've chosen, to skip the react implementaion and do it in a more legacy way, closer to the leaflet implementation itself.

Will merge it, as it's just a renaming. I'm fine with it.

**Pull request merged**
